FriendMVC/Models/Friend.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LTIMVCEntities : DbContext
    {
        public LTIMVCEntities()
            : base("name=LTIMVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Friend> Friends { get; set; }
    }
}

FriendMVC/Models/Friend.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Sandnya Patil\Desktop\HTML LTI\FriendMVC\FriendMVC\Models\Friend.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

FriendMVC/Models/Friend.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int FriendID { get; set; }
        public string FriendName { get; set; }
        public string Place { get; set; }
    }
}

FriendMVC/Models/Friend1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

FriendMVC/Controllers/FriendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FriendMVC.Models;
using System.Web.Security;

namespace FriendMVC.Controllers
{
    public class FriendController : Controller
    {
        LTIMVCEntities db = new LTIMVCEntities();
        // GET: Friend
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Friend F)
        {
            if (ModelState.IsValid)
            {
                db.Friends.Add(F);
                var res = db.SaveChanges();
                if (res > 0)
                    ModelState.AddModelError("", "Added a new Friend");
            }
                return View();
        }
        public ActionResult GetFriend()
        {
            var data = db.Friends.ToList();
            return View(data);

        }

        [HttpGet]
        public ActionResult UpdateFriend(int id)
        {
            var data = db.Friends.Where(x => x.FriendID == id).SingleOrDefault();
            return View(data);
        }

        [HttpPost]

        public ActionResult UpdateFriend()
        {
            int id = Convert.ToInt32(Request.Form["FriendID"]);
            var olddata = db.Friends.Where(x => x.FriendID == id).SingleOrDefault();
            var newname = Request.Form["FriendName"];
            var newplace = Request.Form["Place"];
            olddata.FriendName = newname;
            olddata.Place = newplace;
            var res = db.SaveChanges();
            if (res > 0)
                return RedirectToAction("GetFriend");
            return RedirectToAction("Index");

        }

        [HttpGet]

        public ActionResult DeleteFriend(int id)
        {
            var data = db.Friends.Where(x => x.FriendID == id).SingleOrDefault();
            return View(data);
        }

        [HttpPost]
        public ActionResult DeleteFriend()
        {
            int id = Convert.ToInt32(Request.Form["FriendID"]);
            var delrow = db.Friends.Where(x => x.FriendID == id).SingleOrDefault();
            db.Friends.Remove(delrow);
            var res = db.SaveChanges();
            if (res > 0)
                return RedirectToAction("GetFriend");
            return RedirectToAction("GetFriend");

        }
    }
}

FriendMVC/Views/Friend/DeleteFriend.cshtml
@{
    ViewBag.Title = "DeleteFriend";
}

<h2>DeleteFriend</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div>
        ProductID : <input type="text" name="FriendID" value=@Model.FriendID readonly />
    </div>
    <div>
        ProductName : <input type="text" name="FriendName" value=@Model.FriendName readonly />
    </div>
    <div>
        Product Description : <input type="text" name="Place" value=@Model.Place readonly />
    </div>
    
    <div>
        <input type="submit" value="Delete" />
    </div>
}
@Html.ActionLink("<<Back to Select", "GetFriend")

FriendMVC/Views/Friend/GetFriend.cshtml
@model IEnumerable<FriendMVC.Models.Friend>
@{
    ViewBag.Title = "GetFriend";
}

<h2>GetFriend</h2>
<table border="1">
    <tr>
        <th>Friend ID</th>
        <th>Friend Name</th>
        <th>Place</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>

    @foreach (var m in Model)
    {
        <tr>
            <td>@m.FriendID</td>
            <td>@m.FriendName</td>
            <td>@m.Place</td>
            
            <td>@Html.ActionLink("Edit " + m.FriendID, "UpdateFriend", "Friend", new { id = m.FriendID }, null)</td>
            <td>@Html.ActionLink("Delete " + m.FriendID, "DeleteFriend", "Friend", new { id = m.FriendID }, null)</td>
        </tr>
    }

FriendMVC/Views/Friend/Index.cshtml
@model FriendMVC.Models.Friend
@{
    ViewBag.Title = "Index";
}

<h2>Add a Friend</h2>

<form method="post">
    @Html.ValidationSummary(true)
    <div>
        Friend ID
        @Html.TextBoxFor(x => x.FriendID)
        @Html.ValidationMessageFor(x => x.FriendID)
    </div><br />
    <div>
        Friend Name
        @Html.TextBoxFor(x => x.FriendName)
        @Html.ValidationMessageFor(x => x.FriendName)
    </div><br />
    <div>
        Place
        @Html.TextBoxFor(x => x.Place)
        @Html.ValidationMessageFor(x => x.Place)
    </div><br />
    <input type="submit" value="Add Friend"/>
</form>

FriendMVC/Views/Friend/UpdateFriend.cshtml
@model FriendMVC.Models.Friend
@{ ViewBag.Title = "UpdateFriend"; }

<h2>UpdateFriend</h2>
@using (Html.BeginForm())
{
<div>
Friend ID: <input type="text" name="FriendID" value=@Model.FriendID readonly />
</div>
<div>
 Friend Name: <input type="text" name="FriendName" value=@Model.FriendName />
</div>
 <div>
Friend Name: <input type="text" name="Place" value=@Model.Place />
</div>
<div>
<input type="submit" value="Update" />
</div>
}

FriendMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>